### ISSUE TITLE
How to type some Polish characters?

### ISSUE THREAD

**Issue by nehalem501** [qwerty-fr/qwerty-fr#59]
Hello, when trying the keyboard layout I couldn't figure out how to type "łŁ" characters.

EDIT: Found how to type "żŻ" after creating this issue.

**Comment by devnoname120** [comment]
Hi! There are two ways to type `ł`:

1. Press <kbd>AltGr</kbd><kbd>Shift</kbd><kbd>5</kbd> (this enables the macron diacritic mode). You can then press on the `l` key to obtain the `ł` character. Although this character doesn't actually have a macron, the macron visually looks like a small line similar to the one in the `ł` character. This makes it easy to remember.

2. Press <kbd>AltGr</kbd><kbd>Shift</kbd><kbd>4</kbd> (this enables the currency mode). You can then press on the `l` key to obtain the `ł` character. The reason it's available in the currency mode is that you need it to type `zł` which is the Polish currency.

For `Ł` there is only one way though... Step 1 but press <kbd>Shift</kbd><kbd>l</kbd> instead of just <kbd>l</kbd>.

**Comment by nehalem501** [comment]
It works! Thanks.

**Comment by devnoname120** [comment]
Let me know if it is inconvenient and feel free to share suggestions of placement if you have ideas :)
